workflows:
    hockey-workflow:
        name: Hockey Pipeline
        scripts:
            - name: CICD Started
              script: echo "Welcome to your CICD set up"
            - name: iOS test
              script: |
                xcode-project run-tests \
                --workspace Hockey super quiz.xcworkspace \
                --scheme Hockey super quiz \
                --device "iPhone 11"
                
        definitions:
              env_versions: &env_versions
                xcode: latest
                cocoapods: default

