workflows:
    hockey-workflow:
        name: Hockey Pipeline
        scripts:
            - name: CICD Started
              script: echo "Welcome to your CICD set up"
            - name: iOS test
              script: |
                #!/bin/sh
                set -ex
                xcode-project run-tests \
                    --workspace Hockey_super_quiz.xcworkspace \
                    --scheme Hockey_super_quiz.xcworkspace \
                    --device "iPhone 12"
            
                
                

