workflows:
    hockey-workflow:
        name: Hockey Pipeline
        scripts:
            - name: CICD Started
              script: echo "Welcome to your CICD set up"
            - name: iOS test
              script: |
                xcode-project run-tests \
                    --workspace Hockey super quiz.xcworkspace \
                    --scheme Hockey super quiz \
                    --device "iPhone 11"
#            test_report: build/ios/test/*.xml
              
#            - name: iOS test
#              script: |
#                #!/bin/sh
#                set -ex
#                xcode-project run-tests \
#                    --workspace $XCODE_WORKSPACE \
#                    --scheme $XCODE_SCHEME \
#                    --device "iPhone 12"
            
                
                

